apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-app-demo
  namespace: dev
  labels:
    app: cache-app-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache-app-demo
  template:
    metadata:
      labels:
        app: cache-app-demo
    spec:
      containers:
      - name: cache-app-demo
        image: us-west1-docker.pkg.dev/cache-dev-infra/cache-app/cache-app-dev:fb5dae954be69bc7506734fb8cd7913cbcc8e6e0
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: cache-app-secrets
        - configMapRef:
            name: cache-app-config
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20 