apiVersion: v1
kind: Service
metadata:
  name: cache-app-demo
  namespace: development
  labels:
    app: cache-app-demo
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: cache-app-demo 